lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    token_ttl: 4600 # Durée de validité du token en secondes (?h)

    user_id_claim: 'username'      #the field to use for the JWT subject (re.g, 'username' or 'email')